# Generated by Django 5.1 on 2024-08-19 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_signal', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('currency_pair', models.CharField(blank=True, max_length=6, null=True)),
                ('trader_idea', models.ImageField(blank=True, null=True, upload_to='trader_ideas/')),
                ('post_date_time', models.DateTimeField(blank=True, null=True)),
                ('publisher_trader', models.CharField(blank=True, max_length=50, null=True)),
                ('trader_platform', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trader Idea',
                'verbose_name_plural': 'Trader Ideas',
            },
        ),
    ]
