# Generated by Django 5.1 on 2024-08-19 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MgiCandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_signal', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('signal_candle', models.ImageField(blank=True, null=True, upload_to='signal_candles/')),
                ('hour_candle', models.ImageField(blank=True, null=True, upload_to='hour_candles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candle_pattern', models.CharField(blank=True, choices=[('engulfing', 'Engulfing Candle'), ('small', 'Small Candle'), ('pinbar', 'Pin bar Candle')], max_length=20, null=True)),
                ('fibonacci_level', models.CharField(blank=True, choices=[('38.2%', '38.2%'), ('50%', '50%'), ('61.8%', '61.8%'), ('78.6%', '78.6%')], max_length=5, null=True)),
                ('session', models.CharField(blank=True, choices=[('london', 'London Session'), ('newyork', 'New York Session')], max_length=15, null=True)),
                ('currency_pair', models.CharField(blank=True, max_length=6, null=True)),
                ('five_min_order_block', models.BooleanField(blank=True, default=False, null=True)),
                ('flip_four_hour_candle', models.BooleanField(blank=True, default=False, null=True)),
                ('four_hour_break_of_structure', models.BooleanField(blank=True, default=False, null=True)),
                ('five_min_break_of_structure', models.BooleanField(blank=True, default=False, null=True)),
                ('change_color_ut_alert', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mgi candle',
                'verbose_name_plural': 'Mgi candles',
            },
        ),
    ]
