# Generated by Django 5.1 on 2024-09-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgicandles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgicandles',
            name='breakeven_candle',
            field=models.ImageField(blank=True, null=True, upload_to='breakeven_candle/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='entry_candle',
            field=models.ImageField(blank=True, null=True, upload_to='entry_candle/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='take_profit_candle',
            field=models.ImageField(blank=True, null=True, upload_to='take_profit_candle/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='two_hour_candle',
            field=models.ImageField(blank=True, null=True, upload_to='two_hour_candles/'),
        ),
    ]
