# Generated by Django 5.1 on 2024-09-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgicandles', '0002_mgicandles_breakeven_candle_mgicandles_entry_candle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgicandles',
            name='candle_pattern',
            field=models.CharField(blank=True, choices=[('Engulfing', 'Engulfing Candle'), ('Small Body', 'Small Candle'), ('Pinbar', 'Pin bar Candle')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mgicandles',
            name='session',
            field=models.CharField(blank=True, choices=[('London', 'London Session'), ('Newyork', 'New York Session')], max_length=15, null=True),
        ),
    ]
