# Generated by Django 5.1 on 2024-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgicandles', '0003_alter_mgicandles_candle_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgicandles',
            name='friday_candle',
            field=models.ImageField(blank=True, null=True, upload_to='friday_candles/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='idea_candle',
            field=models.ImageField(blank=True, null=True, upload_to='idea_candles/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='line_graph_candle',
            field=models.ImageField(blank=True, null=True, upload_to='line_graph_candles/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='monday_candle',
            field=models.ImageField(blank=True, null=True, upload_to='monday_candles/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='pips_gained',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='pips_lost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='saturday_candle',
            field=models.ImageField(blank=True, null=True, upload_to='saturday_candles/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='sunday_candle',
            field=models.ImageField(blank=True, null=True, upload_to='sunday_candles/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='thursday_candle',
            field=models.ImageField(blank=True, null=True, upload_to='thursday_candles/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='tuesday_candle',
            field=models.ImageField(blank=True, null=True, upload_to='tuesday_candles/'),
        ),
        migrations.AddField(
            model_name='mgicandles',
            name='wednesday_candle',
            field=models.ImageField(blank=True, null=True, upload_to='wednesday_candles/'),
        ),
    ]
